package bokingfutsal;

import java.awt.Desktop;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;

public class menuutama extends javax.swing.JFrame {

    
       public SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm");
       public Date dt = new Date();
       public Statement st;
       public ResultSet rs;
       public DefaultTableModel tabmodel;
       
       Connection cn = koneksi.koneksi.getKoneksi();

       
    public menuutama() {
        initComponents();
        setLocationRelativeTo(null);
        judul();
        tampildata();
        tglhariini();
        harg();
        kasir();
        hrg_sewa.setText(null);
    }
    
        public void kasir() {
        try {
            st = cn.createStatement();
     
            rs = st.executeQuery("select * from tb_user where tgl = '" + sdf.format(dt) + "'");
            while(rs.next()) {
                nm_ksr.setText(rs.getString("nama"));
            }
        } catch(Exception e) {
            
        }
        nm_ksr.setEnabled(false);
    }   
    
    public void judul(){
    Object[] judul = {"Kd_Booking", "Tgl_Booking", "Kasir","Team","Manager","Status","Harga_Sewa","DP","Tgl_Sewa","Lama","Masuk","Keluar", "Total","sisa","Keterangan"};
    tabmodel = new DefaultTableModel(null, judul);
    tbldata.setModel(tabmodel);
    
    }
   
    public void reset() {
            kd_bkng.setText("");
            nm_tm.setText("");
            mngr.setText("");
            btngmember.clearSelection();  
            hrg_sewa.setText("");
            dp.setText("");
            tgl_sewa.setText("");
            lama_main.setSelectedItem("");
            jam_msk.setSelectedItem("");
            jam_klr.setText("");
            total.setText("");
            sisa.setText("");
            bsimpan.setEnabled(true);
            bupdate.setEnabled(false);
            bdelete.setEnabled(false);
    }
     public void tampildata(){
     try{
        st = cn.createStatement();
        tabmodel.getDataVector().removeAllElements();
        tabmodel.fireTableDataChanged();
        rs = st.executeQuery("select * from tb_menu");
        while (rs.next()){
            Object[] data = {
            rs.getString("kd_booking"),
            rs.getString("tgl_booking"),
            rs.getString("nama_kasir"),
            rs.getString("nama_team"),
            rs.getString("manager"),
            rs.getString("status"),
            rs.getString("harga_sewa"),
            rs.getString("dp"),
            rs.getString("tgl_sewa"),
            rs.getString("lama_bermain"),
            rs.getString("jam_masuk"),
             rs.getString("jam_keluar"),
             rs.getString("total_bayar"),
             rs.getString("sisa"),
            rs.getString("keterangan"),
            };
            tabmodel.addRow(data);
        }
     }catch(Exception a){
         a.printStackTrace();
     }
     }
     public void tglhariini(){
         java.util.Date sekarang = new java.util.Date();
         java.text.SimpleDateFormat tgl = new java.text.SimpleDateFormat("dd/MM/yyyy");
         nm_ksr.setText(tgl.format(sekarang));
         nm_ksr.setEditable(false);
     }
     
     public void harg(){
     int jumlah;
        if(member.isSelected()){
            hrg_sewa.setText("100000");
        } else{
            hrg_sewa.setText("150000");
        }
        hrg_sewa.setEditable(false);
     }
     
     public void totalin(){
     
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngmember = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kd_bkng = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        member = new javax.swing.JRadioButton();
        mngr = new javax.swing.JTextField();
        nonmember = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        hrg_sewa = new javax.swing.JTextField();
        dp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nm_tm = new javax.swing.JTextField();
        tgl_bkng = new javax.swing.JTextField();
        nm_ksr = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lama_main = new javax.swing.JComboBox<>();
        tgl_sewa = new javax.swing.JTextField();
        jam_klr = new javax.swing.JTextField();
        jam_msk = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        sisa = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel2.setText("Kode Booking");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));

        jLabel3.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel3.setText("Tgl.Booking");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel4.setText("Nama Kasir");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel5.setText("Nama Team");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel6.setText("Manager");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        kd_bkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_bkngActionPerformed(evt);
            }
        });
        jPanel1.add(kd_bkng, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 224, -1));

        jLabel7.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btngmember.add(member);
        member.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        member.setText("Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jPanel1.add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        jPanel1.add(mngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 224, -1));

        btngmember.add(nonmember);
        nonmember.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        nonmember.setText("Nonmember");
        nonmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonmemberActionPerformed(evt);
            }
        });
        jPanel1.add(nonmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel8.setText("Harga sewa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        hrg_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrg_sewaActionPerformed(evt);
            }
        });
        jPanel1.add(hrg_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 224, -1));

        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });
        jPanel1.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 224, -1));

        jLabel9.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel9.setText("DP");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        nm_tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_tmActionPerformed(evt);
            }
        });
        jPanel1.add(nm_tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, -1));

        tgl_bkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_bkngActionPerformed(evt);
            }
        });
        jPanel1.add(tgl_bkng, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, -1));
        jPanel1.add(nm_ksr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 220, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 430, 310));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jam Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel11.setText("Tgl.Sewa");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel12.setText("Lama Bermain");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel13.setText("Jam Masuk");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lama_main.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        lama_main.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lama_mainItemStateChanged(evt);
            }
        });
        lama_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lama_mainActionPerformed(evt);
            }
        });
        jPanel2.add(lama_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));
        jPanel2.add(tgl_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 213, -1));

        jam_klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam_klrActionPerformed(evt);
            }
        });
        jPanel2.add(jam_klr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 210, -1));

        jam_msk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jam_msk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam_mskActionPerformed(evt);
            }
        });
        jPanel2.add(jam_msk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 210, -1));

        jLabel19.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel19.setText("Jam Keluar ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 430, 180));

        tbldata.setBackground(new java.awt.Color(0, 204, 204));
        tbldata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbldata.setFont(new java.awt.Font("geektastic", 1, 18)); // NOI18N
        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldata.setGridColor(new java.awt.Color(255, 255, 255));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldata);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 850, 210));

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("BOOKING LAPANGAN FUTSAL");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        bsimpan.setBackground(new java.awt.Color(255, 102, 102));
        bsimpan.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 110, 40));

        bupdate.setBackground(new java.awt.Color(255, 102, 102));
        bupdate.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        bupdate.setText("UPDATE");
        bupdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        bupdate.setEnabled(false);
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel3.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 100, 40));

        bdelete.setBackground(new java.awt.Color(255, 102, 102));
        bdelete.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        bdelete.setText("DELETE");
        bdelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        bdelete.setEnabled(false);
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel3.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 350, 90, 40));

        breset.setBackground(new java.awt.Color(255, 102, 102));
        breset.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        breset.setText("RESET");
        breset.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        jPanel3.add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 100, 40));

        jLabel16.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel16.setText("cari");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 329, -1));

        jLabel17.setFont(new java.awt.Font("geektastic", 1, 18)); // NOI18N
        jLabel17.setText("Total Bayar ");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 20));

        jLabel18.setFont(new java.awt.Font("geektastic", 1, 18)); // NOI18N
        jLabel18.setText("Sisa Pembayaran ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 180, -1));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 190, -1));

        sisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisaActionPerformed(evt);
            }
        });
        jPanel3.add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 190, -1));

        logout.setBackground(new java.awt.Color(255, 102, 102));
        logout.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 570, 110, 40));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        kd_bkng.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 0) + "");
        nm_ksr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 1) + "");
        nm_ksr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 2) + "");
        nm_tm.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 3) + "");
        mngr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 4) + "");
        tabmodel.getValueAt(tbldata.getSelectedRow(), 5);
        String cek = (String) tabmodel.getValueAt(tbldata.getSelectedRow(), 5);
        if("Member".equals(cek)) {
            member.setSelected(true);
        } else {
            nonmember.setSelected(true);
        }
        hrg_sewa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 6) + "") ;
        dp.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 7) + "");
        tgl_sewa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 8) + "");
        lama_main.setSelectedItem(tabmodel.getValueAt(tbldata.getSelectedRow(), 9) + "");
        jam_msk.setSelectedItem(tabmodel.getValueAt(tbldata.getSelectedRow(), 10) + "");
        jam_klr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 11) + "");
        total.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 12) + "");
        sisa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 13) + "");
        
        bsimpan.setEnabled(false);
        bupdate.setEnabled(true);
        bdelete.setEnabled(true);
    }//GEN-LAST:event_tbldataMouseClicked

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        if(kd_bkng.getText().equals("") || nm_ksr.getText().equals("") || nm_ksr.getText().equals("") || nm_tm.getText().equals("") || mngr.getText().equals("") || nm_tm.getText().equals("") || member.getText().equals("") || hrg_sewa.getText().equals("") || dp.getText().equals("") ||
            tgl_sewa.getText().equals("") || lama_main.getSelectedItem().equals("") || jam_msk.getSelectedItem().equals("") || jam_klr.getText().equals("") || total.getText().equals("") || sisa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong");
        } else{
            String memberr = "";
            int jumlah;
            if(member.isSelected()){
                memberr = member.getText();
                hrg_sewa.setText("100000");
            } else{
                memberr = nonmember.getText();
                hrg_sewa.setText("150000");
            }
            String ket; int dep, harg;
            dep = Integer.parseInt(dp.getText());
            harg = Integer.parseInt(hrg_sewa.getText());
            if(dep < harg){
                ket = "belum lunas!!";
                        } else {
                ket = "sudah lunas!!";
            }
            try{
                st = cn.createStatement();
                st.executeUpdate("insert into tb_menu values('" + kd_bkng.getText()+ "','" + tgl_bkng.getText() + "', '" + nm_ksr.getText() + "','" + nm_tm.getText() + "', '" + mngr.getText() + "', '" + memberr + "','" + hrg_sewa.getText()+ "','" + dp.getText()+ "','" + tgl_sewa.getText() + "','" + lama_main.getSelectedItem() + "','" + jam_msk.getSelectedItem() + "','" + jam_klr.getText() + "','" + total.getText() + "','"  + sisa.getText() + "','" + ket + "')");
                 tampildata(); 
                reset();
                JOptionPane.showMessageDialog(null, "Berhasil disimpan!!");
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void hrg_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrg_sewaActionPerformed
        // TODO add your handling code here:
        String memberr, ttl; int totalll;
        if(member.isSelected()){
            memberr = member.getText();
            totalll = 100000;
            ttl = String.valueOf(totalll);
            hrg_sewa.setText(ttl);
        } else{
            memberr = nonmember.getText();
            totalll = 150000;
            ttl = String.valueOf(totalll);
            hrg_sewa.setText(ttl);
        }
        hrg_sewa.setEditable(false);
        
        
    }//GEN-LAST:event_hrg_sewaActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        String memberr;
        int jumlah;
        if(member.isSelected()){
            memberr = member.getText();
            hrg_sewa.setText("100000");
        } else{
            memberr = nonmember.getText();
            hrg_sewa.setText("150000");
        }
        String ket; int dep, totall;
        dep = Integer.parseInt(dp.getText());
        totall = Integer.parseInt(total.getText());
        if(dep < totall){
            ket = "Belum lunas!!";
                    } else {
            ket = "Lunas!!";
        }
        try{
            st = cn.createStatement();
            st.executeUpdate("update tb_menu set tgl_booking = '" + tgl_bkng.getText() + "',  nama_kasir='" + nm_ksr.getText() + "', nama_team='" + nm_tm.getText() + "',manager='" + mngr.getText() + "',status='" + memberr + "', harga_sewa='" + hrg_sewa.getText() + "',dp='" + dp.getText() + "',tgl_sewa='" + tgl_sewa.getText() + "',lama_bermain='" + lama_main.getSelectedItem() + "',jam_masuk='" + jam_msk.getSelectedItem() + "',jam_keluar='" + jam_klr.getText() + "',total_bayar='" + total.getText() + "',sisa='" + sisa.getText() + "',keterangan='" + ket + "' where kd_booking='" + kd_bkng.getText() + "'");
            JOptionPane.showMessageDialog(null, "Data Berhasil  Diupdate!");
            tampildata();
            reset();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
         try{
            int jawab;
            if((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus ?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
         st = cn.createStatement();
         st.executeUpdate("delete from tb_menu where " + "kd_booking='" + tabmodel.getValueAt(tbldata.getSelectedRow(), 0) + "'");
         tampildata();
         reset();
         
        }
        }catch (Exception e){
           e.printStackTrace(); 
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
       if(kd_bkng.getText().equals("") && nm_ksr.getText().equals("") && nm_ksr.getText().equals("") && nm_tm.getText().equals("") && mngr.getText().equals("") && nm_tm.getText().equals("") && member.getText().equals("") && hrg_sewa.getText().equals("") && dp.getText().equals("") &&
            tgl_sewa.getText().equals("") && lama_main.getSelectedItem().equals("") && jam_msk.getSelectedItem().equals("") && jam_klr.getText().equals("") && total.getText().equals("") && sisa.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Data Sudah Kosong!!");
       } else{
           reset();
       }
    }//GEN-LAST:event_bresetActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_totalActionPerformed

    private void sisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sisaActionPerformed

    private void lama_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lama_mainActionPerformed
        // TODO add your handling code here:
        String totall, sisaa; int lama, harg, jml,sisaaa, dep;
        lama = Integer.parseInt((String) lama_main.getSelectedItem());
        dep = Integer.parseInt(dp.getText());
        harg = Integer.parseInt(hrg_sewa.getText());
        jml = lama * harg;
        totall = String.valueOf(jml);
        total.setText(totall);
        total.setEditable(false);
        sisaaa = jml - dep;
        sisaa = String.valueOf(sisaaa);
        sisa.setText(sisaa);
        sisa.setEditable(false);
        
        
    }//GEN-LAST:event_lama_mainActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        hrg_sewa.setText("100000");
    }//GEN-LAST:event_memberActionPerformed

    private void nonmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonmemberActionPerformed
        hrg_sewa.setText("150000");
    }//GEN-LAST:event_nonmemberActionPerformed

    private void lama_mainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lama_mainItemStateChanged
        String totall, sisaa; int lama, harg, jml,sisaaa, dep;
        lama = Integer.parseInt((String) lama_main.getSelectedItem());
        dep = Integer.parseInt(dp.getText());
        harg = Integer.parseInt(hrg_sewa.getText());
        jml = lama * harg;
        totall = String.valueOf(jml);
        total.setText(totall);
        total.setEditable(false);
        sisaaa = jml - dep;
        sisaa = String.valueOf(sisaaa);
        sisa.setText(sisaa);
        sisa.setEditable(false);
        
        String hasil;
        int lila,msk, jmlh, totalll;
        lila = Integer.parseInt((String) lama_main.getSelectedItem());
        msk = Integer.parseInt((String) jam_msk.getSelectedItem());
        totalll = msk + lila;
        hasil = String.valueOf(totalll);
        jam_klr.setText(hasil + ".00");
        
    }//GEN-LAST:event_lama_mainItemStateChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            String sql = "SELECT * FROM tb_menu WHERE kd_booking LIKE '%" + jTextField1.getText() + "%' OR tgl_booking LIKE '%" + jTextField1.getText() + "%' OR nama_kasir LIKE '%" + jTextField1.getText() + "%' OR nama_team LIKE '%" + jTextField1.getText() + "%' OR manager LIKE '%" + jTextField1.getText() + "%' OR status LIKE '%" + jTextField1.getText() + "%' OR harga_sewa LIKE '%" + jTextField1.getText() + "%' OR dp LIKE '%" + jTextField1.getText() + "%' OR tgl_sewa LIKE '%" + jTextField1.getText() + "%' OR lama_bermain LIKE '%" + jTextField1.getText() + "%' OR jam_masuk LIKE '%" + jTextField1.getText() + "%' OR jam_keluar LIKE '%" + jTextField1.getText() + "%' OR total_bayar LIKE '%" + jTextField1.getText() + "%' OR sisa LIKE '%" + jTextField1.getText() + "%' OR keterangan LIKE '%" + jTextField1.getText() + "%'";
            java.sql.Connection con = koneksi.koneksi.getKoneksi();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet rst = stm.executeQuery(sql);
            while(rst.next()) {
                Object[] data = {
                    rst.getString("kd_booking"),
                    rst.getString("tgl_booking"),
                    rst.getString("nama_kasir"),
                    rst.getString("nama_team"),
                    rst.getString("manager"),
                    rst.getString("status"),
                    rst.getString("harga_sewa"),
                    rst.getString("dp"),
                    rst.getString("tgl_sewa"),
                    rst.getString("lama_bermain"),
                    rst.getString("jam_masuk"),
                    rst.getString("jam_keluar"),
                    rst.getString("total_bayar"),
                    rst.getString("sisa"),
                    rst.getString("keterangan"),
                };
                tabmodel.addRow(data);
            }
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       try{
           int log;
           if((log = JOptionPane.showConfirmDialog(null, "Yakin ingin Logout ?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
       login m = new login();
                    m.setVisible(true);
                    this.setVisible(false);
       }
        
       }catch(Exception e){
           e.printStackTrace();
       }  
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         pilihan pl = new pilihan();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jam_klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam_klrActionPerformed

    }//GEN-LAST:event_jam_klrActionPerformed

    private void jam_mskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam_mskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jam_mskActionPerformed

    private void kd_bkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_bkngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kd_bkngActionPerformed

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpActionPerformed

    private void nm_tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm_tmActionPerformed

    private void tgl_bkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_bkngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_bkngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.ButtonGroup btngmember;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField dp;
    private javax.swing.JTextField hrg_sewa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jam_klr;
    private javax.swing.JComboBox<String> jam_msk;
    private javax.swing.JTextField kd_bkng;
    private javax.swing.JComboBox<String> lama_main;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton member;
    private javax.swing.JTextField mngr;
    private javax.swing.JTextField nm_ksr;
    private javax.swing.JTextField nm_tm;
    private javax.swing.JRadioButton nonmember;
    private javax.swing.JTextField sisa;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField tgl_bkng;
    private javax.swing.JTextField tgl_sewa;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
