package bokingfutsal;

import bokingfutsal.menuutama;
import java.awt.Desktop;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class pembayaran extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    DefaultTableModel tabmodel;
    
    Connection cnn = koneksi.koneksi.getKoneksi();
    
    public pembayaran() {
        initComponents();
        setLocationRelativeTo(null);
        reset();
    }
    
    public void reset(){
        kd_bkng.setText("");
        bayarr.setText("");
        sisa.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        kd_bkng = new javax.swing.JTextField();
        sisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bayarr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel1.setText("Kode Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 40));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 70, 30));

        kd_bkng.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kd_bkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_bkngActionPerformed(evt);
            }
        });
        jPanel1.add(kd_bkng, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 30));

        sisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisaActionPerformed(evt);
            }
        });
        jPanel1.add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 290, 30));

        jLabel3.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel3.setText("Pelunasan ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel2.setFont(new java.awt.Font("geektastic", 0, 18)); // NOI18N
        jLabel2.setText("Sisa bayar ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        bayarr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(bayarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 290, 30));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        jButton1.setText("BAYAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, 30));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("geektastic", 0, 14)); // NOI18N
        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 90, 30));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setText("PELUNASAN BOOKING");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, 540, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kd_bkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_bkngActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_kd_bkngActionPerformed

    private void sisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisaActionPerformed

        // 
    }//GEN-LAST:event_sisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(kd_bkng.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Booking tidak boleh kosong");
        }else{
            try{
                st = cnn.createStatement();
                rs = st.executeQuery("select * from tb_menu where kd_booking='" + kd_bkng.getText() +"'");
                while (rs.next()){
                    if(kd_bkng.getText().equals(rs.getString("kd_booking"))) {
                        sisa.setText(rs.getString("sisa"));
                    }
                }
            } catch(Exception a) {
                a.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long kembalian;
        if(bayarr.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Jumlah Pembayaran");
        } else {
            if(Long.parseLong(sisa.getText()) <= Long.parseLong(bayarr.getText())) {
                kembalian =  Long.parseLong(bayarr.getText()) - Long.parseLong(sisa.getText());
                JOptionPane.showMessageDialog(null, "Terima kasih telah berkunjung. Kembaliannya " + kembalian);
                try {
                    st = cnn.createStatement();
                    st.executeUpdate("update tb_menu set sisa = '0', keterangan = 'Lunassssss oy!!' where kd_booking='" + kd_bkng.getText() + "'");
                } catch(Exception a) {
                    a.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Uangnya kurang !!!");
            }
        }
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pilihan pl = new pilihan();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayarr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kd_bkng;
    private javax.swing.JTextField sisa;
    // End of variables declaration//GEN-END:variables
}
